import {validateAssessment,assessmentStudentHtml} from './assessment-model.mjs';
import {answerSheetSvg} from './omr.mjs';
import {printHtml} from './document-export.mjs';
const key='carijo-assessments-v1', e=value=>escapeHtml(value);
let current=null,dirty=false,syncing=false;
export function library(){try{return JSON.parse(localStorage.getItem(key)||'[]').filter(a=>a?.questions?.length);}catch{return [];}}
function store(){const records=library();localStorage.setItem(key,JSON.stringify([current,...records.filter(a=>a.id!==current.id)].slice(0,100)));window.dispatchEvent(new Event('carijo-assessments-changed'));}
export function printDocument(html,title){
 const dialog=document.createElement('dialog');dialog.className='export-preview-dialog assessment-preview';
 dialog.innerHTML='<div class="preview-actions"><strong></strong><button class="primary-button">Imprimir / salvar PDF</button><button class="secondary-button">Fechar</button></div><iframe title="Prévia para impressão"></iframe>';
 dialog.querySelector('strong').textContent=title;const frame=dialog.querySelector('iframe');const printButton=dialog.querySelector('.primary-button');printButton.disabled=true;frame.onload=()=>{printButton.disabled=false;};frame.srcdoc=printHtml(html,title);
 dialog.querySelector('.primary-button').onclick=async()=>{await frame.contentDocument.fonts?.ready;frame.contentWindow.focus();frame.contentWindow.print();};
 dialog.querySelector('.secondary-button').onclick=()=>dialog.close();dialog.addEventListener('close',()=>dialog.remove());document.body.append(dialog);dialog.showModal();
}
export function printSheets(a,students){if(!a.approved)throw new Error('Revise e aprove o gabarito antes de imprimir folhas.');printDocument(students.map(s=>`<section style="break-after:page"><img style="width:174mm;height:239mm;max-width:100%" alt="Folha de respostas" src="data:image/svg+xml;charset=utf-8,${encodeURIComponent(answerSheetSvg(a,s))}"></section>`).join(''),`${a.title} - folhas de respostas`);}
const options=document.createElement('details');options.className='workspace-details';options.innerHTML=`<summary>Personalização pedagógica e correção</summary><div class="field-grid"><label>Complexidade<select id="assessmentDifficulty"><option>Progressiva: fácil, intermediária e desafiadora</option><option>Predominantemente introdutória</option><option>Intermediária</option><option>Desafiadora, sem pegadinhas</option></select></label><label>Composição<select id="assessmentMix"><option>De acordo com o formato escolhido</option><option>Somente múltipla escolha</option><option>Somente questões abertas</option><option>Mista: metade objetiva e metade aberta</option><option>Tarefas práticas com rubrica</option></select></label><label>Nota máxima<input id="assessmentMaximum" type="number" value="10" min="1" max="100" step="0.5"></label><label>Acessibilidade e contexto da turma (sem nomes)<textarea id="assessmentContext" maxlength="3000" placeholder="Leitura mediada, material ampliado, conhecimentos prévios, recursos reais…"></textarea></label></div><p>O gabarito não conhece sua turma. Antes de corrigir alguém, corrija a máquina.</p>`;
document.querySelector('#activityBuilder .generate-row').before(options);
const panel=document.createElement('div');panel.id='assessmentEditor';panel.className='assessment-editor';document.querySelector('#activityAIText').before(panel);
function teacherHtml(a){return `<h2>Gabarito e critérios — ${e(a.title)}</h2><p>${e(a.teacherNotes)}</p>${a.questions.map((q,i)=>`<section><h3>Questão ${i+1} · ${q.points} pontos</h3><p>${q.type==='multiple_choice'?`Alternativa ${String.fromCharCode(65+q.correctIndex)}: ${e(q.options[q.correctIndex])}`:e(q.expectedAnswer)}</p><p>Habilidade: ${e(q.skill)}</p>${q.rubric.map(r=>`<p><strong>${e(r.criterion)} (${r.points} pontos)</strong>: ${e(r.description)}</p>`).join('')}</section>`).join('')}`;}
function render(){
 if(!current){panel.replaceChildren();return;}
 panel.innerHTML=`<div class="workspace-controls"><button data-action="key" class="secondary-button">Gabarito do professor / PDF</button><button data-action="sheet" class="secondary-button">Folha para câmera</button><button data-action="variant" class="secondary-button">Embaralhar alternativas · sem nova chamada à IA</button><button data-action="correct" class="primary-button">Abrir correção</button></div><label class="approval-row"><input type="checkbox" id="approveAssessment" ${current.documentDiverged?'disabled':''} ${current.approved?'checked':''}> Revisei enunciados, alternativas, respostas e pontuações. Aprovo este gabarito.</label><details class="workspace-details"><summary>Editar questões, respostas e rubricas</summary><label>Título<input id="assessmentTitle" value="${e(current.title)}"></label><label>Orientações<textarea id="assessmentInstructions">${e(current.instructions)}</textarea></label><div id="questionEditors">${current.questions.map((q,i)=>`<details class="question-editor"><summary>Questão ${i+1} · ${q.type==='multiple_choice'?'Objetiva':q.type==='open'?'Aberta':'Tarefa'} · ${q.points} pontos</summary><label>Enunciado<textarea data-field="prompt" data-index="${i}">${e(q.prompt)}</textarea></label><label>Pontos<input type="number" min="0.1" max="100" step="0.1" data-field="points" data-index="${i}" value="${q.points}"></label><label>Habilidade<input data-field="skill" data-index="${i}" value="${e(q.skill)}"></label>${q.type==='multiple_choice'?q.options.map((o,j)=>`<label>Alternativa ${String.fromCharCode(65+j)}<input data-field="option" data-index="${i}" data-option="${j}" value="${e(o)}"></label>`).join('')+`<label>Resposta correta<select data-field="correctIndex" data-index="${i}">${q.options.map((_,j)=>`<option value="${j}" ${q.correctIndex===j?'selected':''}>${String.fromCharCode(65+j)}</option>`).join('')}</select></label>`:`<label>Resposta esperada<textarea data-field="expectedAnswer" data-index="${i}">${e(q.expectedAnswer)}</textarea></label>${q.rubric.map((r,j)=>`<fieldset><legend>Critério ${j+1}</legend><label>Critério<input data-field="criterion" data-index="${i}" data-rubric="${j}" value="${e(r.criterion)}"></label><label>Pontos<input type="number" min="0" step="0.1" data-field="rubricPoints" data-index="${i}" data-rubric="${j}" value="${r.points}"></label><label>Descrição<textarea data-field="description" data-index="${i}" data-rubric="${j}">${e(r.description)}</textarea></label></fieldset>`).join('')}`}</details>`).join('')}</div><button data-action="apply" class="primary-button">Aplicar edição e atualizar documento</button></details><p id="assessmentMessage" role="status">Material do estudante abaixo. Gabarito e rubricas ficam separados.</p>`;
 panel.querySelector('#approveAssessment').onchange=event=>{try{validateAssessment(current);current.approved=event.target.checked;store();}catch(error){event.target.checked=false;message(error.message);}};
 panel.querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>{try{
  const action=button.dataset.action;
  if(action==='key')printDocument(teacherHtml(current),current.title+' - gabarito do professor');
  if(action==='sheet')printSheets(current,[{machineId:0,name:'',registration:''}]);
  if(action==='correct')window.CarijoCorrections?.open(current.id);
  if(action==='apply')applyEdits();
  if(action==='variant'){current=structuredClone(current);current.id=crypto.randomUUID();current.approved=false;current.title+=' · versão alternativa';for(const q of current.questions.filter(q=>q.type==='multiple_choice')){const rows=q.options.map((text,i)=>({text,correct:i===q.correctIndex}));for(let i=rows.length-1;i>0;i--){const j=Math.floor(crypto.getRandomValues(new Uint32Array(1))[0]/4294967296*(i+1));[rows[i],rows[j]]=[rows[j],rows[i]];}q.options=rows.map(r=>r.text);q.correctIndex=rows.findIndex(r=>r.correct);}sync();}
 }catch(error){message(error.message);}});
 panel.querySelectorAll('input:not(#approveAssessment),textarea,select').forEach(field=>field.addEventListener('input',()=>{dirty=true;current.approved=false;panel.querySelector('#approveAssessment').checked=false;panel.querySelector('#approveAssessment').disabled=true;message('Aplique as edições antes de aprovar o novo gabarito.');store();}));
}
function message(text){panel.querySelector('#assessmentMessage').textContent=text;}
function applyEdits(){const draft=structuredClone(current);draft.title=panel.querySelector('#assessmentTitle').value;draft.instructions=panel.querySelector('#assessmentInstructions').value;panel.querySelectorAll('[data-field]').forEach(field=>{const q=draft.questions[Number(field.dataset.index)],name=field.dataset.field;if(name==='option')q.options[Number(field.dataset.option)]=field.value;else if(field.dataset.rubric!==undefined)q.rubric[Number(field.dataset.rubric)][name==='rubricPoints'?'points':name]=name==='rubricPoints'?Number(field.value):field.value;else q[name]=['points','correctIndex'].includes(name)?Number(field.value):field.value;});current={...validateAssessment(draft),approved:false};sync();}
function sync(){dirty=false;current.documentDiverged=false;store();$('#activityOutputTitle').textContent=current.title;$('#activityAIText').innerHTML=assessmentStudentHtml(current,e);currentActivityText=$('#activityAIText').innerText;render();syncing=true;try{$('#activityAIText').dispatchEvent(new Event('input',{bubbles:true}));}finally{syncing=false;}}
async function generate(){
 if(!state.classes.length){toast('Cadastre uma turma antes de gerar.');return;}
 const maximum=Number($('#assessmentMaximum').value);if(!Number.isFinite(maximum)||maximum<=0||maximum>100){toast('Informe nota máxima entre 1 e 100.');return;}
 if(!await confirmGeneration())return;const button=$('#generateActivity');button.disabled=true;button.textContent='Gerando avaliação personalizada…';$('#activityOutput').classList.remove('hidden');
 try{const prompt=activityPrompt()+`\nPersonalização: ${$('#assessmentDifficulty').value}. Composição: ${$('#assessmentMix').value}. Contexto informado: ${$('#assessmentContext').value}. Gere entre 1 e 30 itens. Entregue a estrutura JSON solicitada: multiple_choice para alternativas (2 a 5), open para resposta escrita, task para atividades práticas. Em open/task, options=[] e correctIndex=-1; rubric contém critérios com pontos que somam exatamente points. Enunciados completos e autossuficientes. Não inclua resposta nos enunciados. Gabarito, justificativa e orientações do professor em campos separados. Dificuldades easy/medium/hard. Cada habilidade deve corresponder ao recorte informado, sem inventar códigos.`;
 const {data,error}=await invokeFreeGeneration(prompt,'activity',{outputFormat:'assessment'});if(error)throw error;if(!data.assessment)throw new Error('O servidor não entregou uma avaliação estruturada. Atualize a função de geração.');
 current={...validateAssessment(data.assessment),id:crypto.randomUUID(),approved:false,maximum,diagnostic:$('#activityType').value==='diagnostic',classInfo:{...state.classes.find(x=>x.id===Number($('#activityClassSelect').value)),quarter:$('#activityQuarter').value},createdAt:new Date().toISOString()};sync();window.CarijoEditor?.generated('activity');notifyGenerationUsage(data.usage);$('#activityOutput').scrollIntoView({behavior:'smooth'});
 }catch(error){const notice=$('#activityUsageNotice');notice.classList.remove('hidden');notice.textContent=`A nova avaliação não foi concluída: ${error.message||'Falha desconhecida'}. Se há um documento abaixo, ele é a versão anterior.`;}finally{generationInProgress=false;button.disabled=false;button.textContent='Gerar nova avaliação';}
}
$('#activityAIText').addEventListener('input',()=>{if(current&&!syncing){current.approved=false;current.documentDiverged=true;store();render();message('O documento livre foi alterado. Para manter a folha e o gabarito coerentes, edite as questões acima e clique em Aplicar edição; isso reconstitui o material do estudante.');}});
const saved=document.createElement('details');saved.className='workspace-details';saved.innerHTML='<summary>Biblioteca de avaliações neste dispositivo</summary><label>Avaliação salva<select id="assessmentLibrary"></select></label><button id="openAssessmentLibrary" class="secondary-button">Abrir para revisar</button>';options.after(saved);
function refreshSaved(){$('#assessmentLibrary').innerHTML=library().map(a=>`<option value="${e(a.id)}">${e(a.title)}</option>`).join('')||'<option value="">Nenhuma avaliação estruturada salva</option>';}
$('#openAssessmentLibrary').onclick=()=>{const found=library().find(x=>x.id===$('#assessmentLibrary').value);if(!found)return;current=validateAssessment(found);sync();if(current.classInfo){const c=current.classInfo;window.CarijoEditor?.open({id:'local-'+current.id,class_id:c.id,class_name:c.name,subject:c.subject,plan_type:'activity',title:current.title,period_label:`${c.quarter}º trimestre`,plan_data:{assessment:current}},'activity');window.CarijoEditor?.save('activity');}else window.CarijoEditor?.generated('activity');$('#activityOutput').classList.remove('hidden');$('#activityOutput').scrollIntoView({behavior:'smooth'});};window.addEventListener('carijo-assessments-changed',refreshSaved);refreshSaved();
window.CarijoAssessments={generate,library,current:()=>current,restore:a=>{current=a?{...validateAssessment(a)}:null;dirty=false;if(current)store();render();},restoreLibrary:records=>{const valid=records.map(a=>({...validateAssessment(a),approved:false}));localStorage.setItem(key,JSON.stringify(valid.slice(0,100)));refreshSaved();},printSheets};
