import {validateAssessment,assessmentStudentHtml} from './assessment-model.mjs';
import {answerSheetSvg} from './omr.mjs';
import {printHtml} from './document-export.mjs';
import {planSource,sourcePrompt} from './assessment-source.mjs';
const key='carijo-assessments-v1', e=value=>escapeHtml(value);
let current=null,dirty=false,syncing=false;
let source=null;
const sourcePanel=document.createElement('section');sourcePanel.className='assessment-source-card';
sourcePanel.innerHTML='<h2>Do planejamento à avaliação</h2><p>Use um documento salvo como ponto de partida ou continue com uma criação independente.</p><div class="workspace-controls"><label>Planejamento salvo<select id="assessmentSourcePlan"></select></label><button type="button" id="useAssessmentSource" class="secondary-button">Usar planejamento</button></div><div id="assessmentSourceDetails" class="hidden"><p id="assessmentSourceLabel" role="status"></p><label>Recorte de conteúdos, objetivos ou aulas<textarea id="assessmentSourceScope" maxlength="3000" placeholder="Ex.: somente as aulas de jogos cooperativos. Desmarque abaixo as habilidades que não serão avaliadas."></textarea></label><p>O planejamento é uma fotografia da versão escolhida. Alterações posteriores nele não modificam esta avaliação. Não inclua dados pessoais de estudantes.</p><button type="button" id="clearAssessmentSource" class="secondary-button">Continuar sem vínculo com planejamento</button></div>';
document.querySelector('#activityBuilder .form-flow').prepend(sourcePanel);
function refreshSources(){const selected=$('#assessmentSourcePlan').value;const records=readDeviceDocuments().filter(r=>r.plan_type==='quarter'||r.plan_type==='fortnight');$('#assessmentSourcePlan').innerHTML=records.map(r=>`<option value="${e(r.id)}">${e(r.title)} · ${e(r.class_name)} · ${e(r.subject)}</option>`).join('')||'<option value="">Nenhum planejamento salvo neste dispositivo</option>';if(records.some(r=>r.id===selected))$('#assessmentSourcePlan').value=selected;return records;}
function clearSource(){source=null;$('#assessmentSourceDetails').classList.add('hidden');}
function useSource(record){
 const candidate=planSource(record);
 let item=state.classes.find(c=>c.id===Number(candidate.classId)&&c.subject===candidate.subject&&c.name===candidate.className)||state.classes.find(c=>c.name===candidate.className&&c.subject===candidate.subject);
 if(!item){if(!confirm('A turma deste planejamento não está cadastrada. Adicionar a turma para preparar a avaliação?'))return;item={id:Date.now(),name:candidate.className,subject:candidate.subject,lessons:1,schedule:[],notes:''};state.classes.push(item);saveLocalData();}
 openActivityBuilder();source=candidate;
 $('#activityClassSelect').value=String(item.id);syncActivityGrade();
 $('#activityQuarter').value=String(source.quarter);const duration=$('#activityDuration');if(![...duration.options].some(o=>o.value===String(source.duration))){const option=document.createElement('option');option.value=String(source.duration);option.textContent=`${source.duration} minutos · planejamento`;duration.append(option);}duration.value=String(source.duration);
 $('#activityTheme').value=source.title;$('#activityGoal').value='';$('#assessmentContext').value=source.classroomContext;
 const choice=[...$('#activityResource').options].find(o=>source.resources.includes(o.value));if(choice)$('#activityResource').value=choice.value;
 state.activitySkills=new Set(source.skills.map(skillKey));renderActivitySkills();renderActivityProfileSummary();
 $('#assessmentSourceScope').value='';$('#assessmentSourceLabel').textContent=`Origem: ${source.title} · ${source.className} · ${source.subject}. Habilidades herdadas: ${source.skills.length}.`;
 $('#assessmentSourceDetails').classList.remove('hidden');sourcePanel.scrollIntoView({behavior:'smooth',block:'start'});
}
$('#useAssessmentSource').onclick=()=>{try{const record=refreshSources().find(r=>r.id===$('#assessmentSourcePlan').value);if(record)useSource(record);}catch(error){toast(error.message);}};
$('#clearAssessmentSource').onclick=()=>{clearSource();state.activitySkills=new Set();renderActivitySkills();};
['#activityClassSelect','#activityQuarter','#activityGrade'].forEach(selector=>$(selector).addEventListener('change',()=>{if(source){clearSource();state.activitySkills=new Set();renderActivitySkills();toast('O recorte mudou. O vínculo com o planejamento foi removido.');}}));
const fromPlan=document.createElement('button');fromPlan.type='button';fromPlan.className='secondary-button';fromPlan.textContent='Criar atividade / avaliação deste planejamento';
document.querySelector('.result-actions').prepend(fromPlan);
fromPlan.onclick=()=>{try{const record=window.CarijoEditor?.sourcePlan();if(!record)throw new Error('Gere ou abra um planejamento primeiro.');useSource(record);}catch(error){toast(error.message);}};
refreshSources();$('#assessmentSourcePlan').addEventListener('focus',refreshSources);
export function library(){try{return JSON.parse(localStorage.getItem(key)||'[]').filter(a=>a?.questions?.length);}catch{return [];}}
function store(){const records=library();localStorage.setItem(key,JSON.stringify([current,...records.filter(a=>a.id!==current.id)].slice(0,100)));window.dispatchEvent(new Event('carijo-assessments-changed'));}
export function printDocument(html,title){
 const dialog=document.createElement('dialog');dialog.className='export-preview-dialog assessment-preview';
 dialog.innerHTML='<div class="preview-actions"><strong></strong><button class="primary-button">Imprimir / salvar PDF</button><button class="secondary-button">Fechar</button></div><iframe title="Prévia para impressão"></iframe>';
 dialog.querySelector('strong').textContent=title;const frame=dialog.querySelector('iframe');const printButton=dialog.querySelector('.primary-button');printButton.disabled=true;frame.onload=()=>{printButton.disabled=false;};frame.srcdoc=printHtml(html,title);
 dialog.querySelector('.primary-button').onclick=async()=>{await frame.contentDocument.fonts?.ready;frame.contentWindow.focus();frame.contentWindow.print();};
 dialog.querySelector('.secondary-button').onclick=()=>dialog.close();dialog.addEventListener('close',()=>dialog.remove());document.body.append(dialog);dialog.showModal();
}
export function printSheets(a,students){if(!a.approved)throw new Error('Revise e aprove o gabarito antes de imprimir folhas.');printDocument(students.map(s=>`<section style="break-after:page"><img style="width:160mm;height:auto;max-width:100%" alt="Folha de respostas compacta" src="data:image/svg+xml;charset=utf-8,${encodeURIComponent(answerSheetSvg(a,s))}"></section>`).join(''),`${a.title} - folhas de respostas`);}
const options=document.createElement('details');options.className='workspace-details';options.innerHTML=`<summary>Personalização pedagógica e correção</summary><div class="field-grid"><label>Complexidade<select id="assessmentDifficulty"><option>Progressiva: fácil, intermediária e desafiadora</option><option>Predominantemente introdutória</option><option>Intermediária</option><option>Desafiadora, sem pegadinhas</option></select></label><label>Composição<select id="assessmentMix"><option>De acordo com o formato escolhido</option><option>Somente múltipla escolha</option><option>Somente questões abertas</option><option>Mista: metade objetiva e metade aberta</option><option>Tarefas práticas com rubrica</option></select></label><label>Nota máxima<input id="assessmentMaximum" type="number" value="10" min="1" max="100" step="0.5"></label><label>Acessibilidade e contexto da turma (sem nomes)<textarea id="assessmentContext" maxlength="3000" placeholder="Leitura mediada, material ampliado, conhecimentos prévios, recursos reais…"></textarea></label></div><p>O gabarito não conhece sua turma. Antes de corrigir alguém, corrija a máquina.</p>`;
document.querySelector('#activityBuilder .generate-row').before(options);
const panel=document.createElement('div');panel.id='assessmentEditor';panel.className='assessment-editor';document.querySelector('#activityAIText').before(panel);
function teacherHtml(a){return `<h2>Gabarito e critérios — ${e(a.title)}</h2><p>${e(a.teacherNotes)}</p>${a.questions.map((q,i)=>`<section><h3>Questão ${i+1} · ${q.points} pontos</h3><p>${q.type==='multiple_choice'?`Alternativa ${String.fromCharCode(65+q.correctIndex)}: ${e(q.options[q.correctIndex])}`:e(q.expectedAnswer)}</p><p>Habilidade: ${e(q.skill)}</p>${q.rubric.map(r=>`<p><strong>${e(r.criterion)} (${r.points} pontos)</strong>: ${e(r.description)}</p>`).join('')}</section>`).join('')}`;}
function render(){
 if(!current){panel.textContent='Este documento não possui uma estrutura de questões e gabarito vinculada. A correção por câmera está indisponível; gere uma avaliação estruturada para utilizá-la.';return;}
 panel.innerHTML=`<div class="workspace-controls"><button data-action="key" class="secondary-button">Gabarito do professor / PDF</button><button data-action="sheet" class="secondary-button">Folha para câmera</button><button data-action="variant" class="secondary-button">Embaralhar alternativas · sem nova chamada à IA</button><button data-action="correct" class="primary-button">Abrir correção</button></div><label class="approval-row"><input type="checkbox" id="approveAssessment" ${current.documentDiverged?'disabled':''} ${current.approved?'checked':''}> Revisei enunciados, alternativas, respostas e pontuações. Aprovo este gabarito.</label><details class="workspace-details"><summary>Editar questões, respostas e rubricas</summary><label>Título<input id="assessmentTitle" value="${e(current.title)}"></label><label>Orientações<textarea id="assessmentInstructions">${e(current.instructions)}</textarea></label><div id="questionEditors">${current.questions.map((q,i)=>`<details class="question-editor"><summary>Questão ${i+1} · ${q.type==='multiple_choice'?'Objetiva':q.type==='open'?'Aberta':'Tarefa'} · ${q.points} pontos</summary><label>Enunciado<textarea data-field="prompt" data-index="${i}">${e(q.prompt)}</textarea></label><label>Pontos<input type="number" min="0.1" max="100" step="0.1" data-field="points" data-index="${i}" value="${q.points}"></label><label>Habilidade<input data-field="skill" data-index="${i}" value="${e(q.skill)}"></label>${q.type==='multiple_choice'?q.options.map((o,j)=>`<label>Alternativa ${String.fromCharCode(65+j)}<input data-field="option" data-index="${i}" data-option="${j}" value="${e(o)}"></label>`).join('')+`<label>Resposta correta<select data-field="correctIndex" data-index="${i}">${q.options.map((_,j)=>`<option value="${j}" ${q.correctIndex===j?'selected':''}>${String.fromCharCode(65+j)}</option>`).join('')}</select></label>`:`<label>Resposta esperada<textarea data-field="expectedAnswer" data-index="${i}">${e(q.expectedAnswer)}</textarea></label>${q.rubric.map((r,j)=>`<fieldset><legend>Critério ${j+1}</legend><label>Critério<input data-field="criterion" data-index="${i}" data-rubric="${j}" value="${e(r.criterion)}"></label><label>Pontos<input type="number" min="0" step="0.1" data-field="rubricPoints" data-index="${i}" data-rubric="${j}" value="${r.points}"></label><label>Descrição<textarea data-field="description" data-index="${i}" data-rubric="${j}">${e(r.description)}</textarea></label></fieldset>`).join('')}`}</details>`).join('')}</div><button data-action="apply" class="primary-button">Aplicar edição e atualizar documento</button></details><p id="assessmentMessage" role="status">Material do estudante abaixo. Gabarito e rubricas ficam separados.</p>`;
 panel.querySelector('#approveAssessment').onchange=event=>{try{validateAssessment(current);current.approved=event.target.checked;store();window.CarijoEditor?.save('activity');}catch(error){event.target.checked=false;message(error.message);}};
 panel.querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>{try{
  const action=button.dataset.action;
  if(action==='key')printDocument(teacherHtml(current),current.title+' - gabarito do professor');
  if(action==='sheet')printSheets(current,[{machineId:0,name:'',registration:''}]);
  if(action==='correct')window.CarijoCorrections?.open(current.id);
  if(action==='apply')applyEdits();
  if(action==='variant'){current=structuredClone(current);current.id=crypto.randomUUID();current.approved=false;current.title+=' · versão alternativa';for(const q of current.questions.filter(q=>q.type==='multiple_choice')){const rows=q.options.map((text,i)=>({text,correct:i===q.correctIndex}));for(let i=rows.length-1;i>0;i--){const j=Math.floor(crypto.getRandomValues(new Uint32Array(1))[0]/4294967296*(i+1));[rows[i],rows[j]]=[rows[j],rows[i]];}q.options=rows.map(r=>r.text);q.correctIndex=rows.findIndex(r=>r.correct);}sync();}
 }catch(error){message(error.message);}});
 panel.querySelectorAll('input:not(#approveAssessment),textarea,select').forEach(field=>field.addEventListener('input',()=>{dirty=true;current.approved=false;panel.querySelector('#approveAssessment').checked=false;panel.querySelector('#approveAssessment').disabled=true;message('Aplique as edições antes de aprovar o novo gabarito.');store();}));
 const add=document.createElement('div');add.className='workspace-controls';add.innerHTML='<label>Nova questão<select><option value="multiple_choice">Objetiva</option><option value="open">Aberta</option><option value="task">Tarefa prática</option></select></label><button class="secondary-button">Adicionar questão sem usar a IA</button>';panel.querySelector('#questionEditors').before(add);
 add.querySelector('button').onclick=()=>{try{const type=add.querySelector('select').value;if(current.questions.length>=30)throw new Error('O limite da folha de respostas é de 30 questões.');if(dirty)applyEdits();current.questions.push({type,prompt:'Escreva o enunciado completo desta questão.',options:type==='multiple_choice'?['Alternativa A','Alternativa B']:[],correctIndex:type==='multiple_choice'?0:-1,expectedAnswer:'Informe a resposta esperada ou a justificativa.',skill:'Informe a habilidade trabalhada.',difficulty:'medium',points:1,rubric:type==='multiple_choice'?[]:[{criterion:'Critério de correção',points:1,description:'Descreva o que caracteriza uma resposta adequada.'}]});current=validateAssessment({...current,approved:false});sync();}catch(error){message(error.message);}};
 panel.querySelectorAll('#questionEditors > .question-editor').forEach((details,i)=>{const remove=document.createElement('button');remove.className='secondary-button';remove.textContent='Remover questão';remove.onclick=()=>{try{if(current.questions.length===1)throw new Error('Mantenha pelo menos uma questão.');if(!confirm('Remover esta questão? O gabarito e as folhas anteriores deixarão de corresponder à avaliação.'))return;if(dirty)applyEdits();current.questions.splice(i,1);current=validateAssessment({...current,approved:false});sync();}catch(error){message(error.message);}};details.append(remove);});
}
function message(text){panel.querySelector('#assessmentMessage').textContent=text;}
function applyEdits(){const draft=structuredClone(current);draft.title=panel.querySelector('#assessmentTitle').value;draft.instructions=panel.querySelector('#assessmentInstructions').value;panel.querySelectorAll('[data-field]').forEach(field=>{const q=draft.questions[Number(field.dataset.index)],name=field.dataset.field;if(name==='option')q.options[Number(field.dataset.option)]=field.value;else if(field.dataset.rubric!==undefined)q.rubric[Number(field.dataset.rubric)][name==='rubricPoints'?'points':name]=name==='rubricPoints'?Number(field.value):field.value;else q[name]=['points','correctIndex'].includes(name)?Number(field.value):field.value;});current={...validateAssessment(draft),approved:false};sync();}
function sync(notify=true){dirty=false;current.documentDiverged=false;store();$('#activityOutputTitle').textContent=current.title;$('#activityAIText').innerHTML=assessmentStudentHtml(current,e);currentActivityText=$('#activityAIText').innerText;render();syncing=true;try{if(notify)$('#activityAIText').dispatchEvent(new Event('input',{bubbles:true}));}finally{syncing=false;}}
async function generate(){
 if(!state.classes.length){toast('Cadastre uma turma antes de gerar.');return;}
 const maximum=Number($('#assessmentMaximum').value);if(!Number.isFinite(maximum)||maximum<=0||maximum>100){toast('Informe nota máxima entre 1 e 100.');return;}
 if(!await confirmGeneration())return;const button=$('#generateActivity');button.disabled=true;button.textContent='Gerando avaliação personalizada…';$('#activityOutput').classList.remove('hidden');
 try{const prompt=activityPrompt()+`\nPersonalização: ${$('#assessmentDifficulty').value}. Composição: ${$('#assessmentMix').value}. Contexto informado: ${$('#assessmentContext').value}. Gere entre 1 e 30 itens. Entregue a estrutura JSON solicitada: multiple_choice para alternativas (2 a 5), open para resposta escrita, task para atividades práticas. Em open/task, options=[] e correctIndex=-1; rubric contém critérios com pontos que somam exatamente points. Enunciados completos e autossuficientes. Não inclua resposta nos enunciados. Gabarito, justificativa e orientações do professor em campos separados. Dificuldades easy/medium/hard. Cada habilidade deve corresponder ao recorte informado, sem inventar códigos.`;
 const origin=source?{...structuredClone(source),scope:$('#assessmentSourceScope').value,selectedSkills:skillsForActivity().filter(s=>state.activitySkills.has(skillKey(s))).map(s=>({...s}))}:null;
 const resume={kind:'activity',maximum,sourcePlan:origin,diagnostic:$('#activityType').value==='diagnostic',classInfo:{...state.classes.find(x=>x.id===Number($('#activityClassSelect').value)),quarter:$('#activityQuarter').value}};
 const {data,error}=await invokeFreeGeneration(prompt+sourcePrompt(origin,origin?.scope),'activity',{outputFormat:'assessment',resume});if(error)throw error;if(!data.assessment)throw new Error('O servidor não entregou uma avaliação estruturada. Atualize a função de geração.');
 current={...validateAssessment(data.assessment),id:crypto.randomUUID(),approved:false,maximum,sourcePlan:origin,diagnostic:$('#activityType').value==='diagnostic',classInfo:{...state.classes.find(x=>x.id===Number($('#activityClassSelect').value)),quarter:$('#activityQuarter').value},createdAt:new Date().toISOString()};sync(false);window.CarijoEditor?.generated('activity');notifyGenerationUsage(data.usage);window.CarijoRecovery?.complete();$('#activityOutput').scrollIntoView({behavior:'smooth'});
 }catch(error){const notice=$('#activityUsageNotice');notice.classList.remove('hidden');notice.textContent=`A nova avaliação não foi concluída: ${error.message||'Falha desconhecida'}. Se há um documento abaixo, ele é a versão anterior.`;}finally{generationInProgress=false;button.disabled=false;button.textContent='Gerar nova avaliação';}
}
$('#activityAIText').addEventListener('input',()=>{if(current&&!syncing){current.approved=false;current.documentDiverged=true;store();render();message('O documento livre foi alterado. Para manter a folha e o gabarito coerentes, edite as questões acima e clique em Aplicar edição; isso reconstitui o material do estudante.');}});
const saved=document.createElement('details');saved.className='workspace-details';saved.innerHTML='<summary>Biblioteca de avaliações neste dispositivo</summary><label>Avaliação salva<select id="assessmentLibrary"></select></label><button id="openAssessmentLibrary" class="secondary-button">Abrir para revisar</button>';options.after(saved);
function refreshSaved(){$('#assessmentLibrary').innerHTML=library().map(a=>`<option value="${e(a.id)}">${e(a.title)}</option>`).join('')||'<option value="">Nenhuma avaliação estruturada salva</option>';}
$('#openAssessmentLibrary').onclick=()=>{const found=library().find(x=>x.id===$('#assessmentLibrary').value);if(!found)return;restore(found);sync(false);if(current.classInfo){const c=current.classInfo;window.CarijoEditor?.open({id:'local-'+current.id,class_id:c.id,class_name:c.name,subject:c.subject,plan_type:'activity',title:current.title,period_label:`${c.quarter}º trimestre`,plan_data:{assessment:current}},'activity');window.CarijoEditor?.save('activity');}else window.CarijoEditor?.generated('activity');$('#activityOutput').classList.remove('hidden');$('#activityOutput').scrollIntoView({behavior:'smooth'});};window.addEventListener('carijo-assessments-changed',refreshSaved);refreshSaved();
function restore(a,invalidate=false){
 current=a?{...validateAssessment(structuredClone(a)),...(invalidate?{approved:false}: {})}:null;dirty=false;
 // A restored key receives a new identity: old printed sheets and recorded grades
 // must never become valid again merely because an earlier key was restored.
 if(current&&invalidate)current.id=crypto.randomUUID();
 clearSource();if(current?.sourcePlan){
  const origin=structuredClone(current.sourcePlan),item=state.classes.find(c=>c.name===origin.className&&c.subject===origin.subject);
  if(item){source=origin;renderActivityClassOptions();$('#activityClassSelect').value=String(item.id);syncActivityGrade();$('#activityQuarter').value=String(source.quarter);state.activitySkills=new Set((source.selectedSkills||source.skills).map(skillKey));renderActivitySkills();renderActivityProfileSummary();}
  $('#assessmentSourceScope').value=origin.scope||'';$('#assessmentSourceLabel').textContent=`Origem preservada: ${origin.title} · ${origin.className} · ${origin.subject}${item?'':'. Turma ausente: o vínculo não será usado em novas gerações.'}`;$('#assessmentSourceDetails').classList.remove('hidden');
 }
 if(current)store();render();
}
window.CarijoAssessments={recover:async(data,resume)=>{current={...validateAssessment(data.assessment),id:crypto.randomUUID(),approved:false,maximum:resume.maximum,diagnostic:resume.diagnostic,sourcePlan:resume.sourcePlan,classInfo:resume.classInfo,createdAt:new Date().toISOString()};sync(false);const c=current.classInfo;window.CarijoEditor.open({id:'local-'+current.id,class_id:c.id,class_name:c.name,subject:c.subject,plan_type:'activity',title:current.title,period_label:`${c.quarter}º trimestre`,plan_data:{assessment:current}},'activity');await window.CarijoEditor.save('activity');showScreen('activityBuilder');$('#activityOutput').classList.remove('hidden');},generate,library,current:()=>current,clearSource,sourceSkills:()=>source?.skills||null,
 invalidateDocument:()=>{if(current&&!syncing){current.approved=false;current.documentDiverged=true;store();}},
 restore:a=>restore(a),restoreVersion:a=>restore(a,true),
 restoreLibrary:records=>{const valid=records.map(a=>({...validateAssessment(a),approved:false}));localStorage.setItem(key,JSON.stringify(valid.slice(0,100)));refreshSaved();},printSheets};
