import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import { webcrypto } from 'node:crypto';

const source = readFileSync(new URL('../app.js', import.meta.url), 'utf8');
const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const ids = new Set([...html.matchAll(/\bid="([^"]+)"/g)].map(item => item[1]));
const nodes = new Map();
const storage = new Map();
const document = {addEventListener(){},querySelector(selector){
  if (!selector.startsWith('#')) return null;
  const id = selector.slice(1);
  assert.ok(ids.has(id), `Elemento ausente no formulário: ${id}`);
  if (!nodes.has(id)) nodes.set(id,{value:'',textContent:'',innerHTML:'',classList:{add(){},remove(){},toggle(){}},addEventListener(){}});
  return nodes.get(id);
},querySelectorAll(){return []}};
const context = vm.createContext({document,window:{},crypto:webcrypto,location:{protocol:'http:',origin:'http://localhost:3000',pathname:'/'},localStorage:{getItem:key => storage.get(key) || null,setItem:(key,value) => storage.set(key,value)},console});
vm.runInContext(source,context);
vm.runInContext(`renderManualStart = () => {}; renderClassOptions = () => {}; showModalElement = () => {}; hideModalElement = () => {}; showScreen = id => { globalThis.screen = id; }; openActivityBuilder = () => {globalThis.activityOpened = true}; syncActivityGrade = () => {}; renderActivitySkills = () => {}; renderActivityProfileSummary = () => {};`,context);
const run = code => vm.runInContext(code,context);
run('initializeHomeActions(); openQuickStart("plan")');
nodes.get('quickClass').value = 'new';
nodes.get('quickSubject').value = 'Educação Física';
nodes.get('quickGrade').value = '6';
document.querySelector('#quickLessons').value = '3';
run('continueQuickStart()');
assert.equal(run('state.classes.length'),1);
assert.equal(run('state.classes[0].subject'),'Educação Física');
assert.equal(run('screen'),'choose');
assert.equal(nodes.get('recorteClass').value,'1');
run('openQuickStart("activity")');
nodes.get('quickClass').value='1';
run('continueQuickStart()');
assert.equal(run('activityOpened'),true);
assert.equal(run('state.classes.length'),1,'Turma salva não deve ser duplicada');
run('openQuickStart("plan")');
nodes.get('quickClass').value='new';
nodes.get('quickLessons').value='0';
run('continueQuickStart()');
assert.equal(run('state.classes.length'),1,'Carga inválida não cria turma');
run(`currentPlanId = null; storeDeviceDocument({title:'Primeiro',plan_type:'quarter',document_html:'<p>Texto</p>'}); storeDeviceDocument({title:'Editado',plan_type:'quarter',document_html:'<p>Texto editado</p>'})`);
assert.equal(run('readDeviceDocuments().length'),1,'Salvar edição atualiza o mesmo documento local');
assert.equal(run('readDeviceDocuments()[0].title'),'Editado');
console.log('Entrada direta, turma existente, validação de carga e histórico local verificados.');
